config/routes.rb
Rails.application.routes.draw do
  post 'invitations/send_all' => 'invitations#send_all'
  resources :groups
  resources :invitations
  resources :guests
  devise_for :users
  resources :rsvps
  root 'rsvps#index'

end

app/models/guest.rb
class Guest < ActiveRecord::Base
  has_many :grouped_guests
  has_many :groups, through: :grouped_guests
  def full_name
    first_name + ' ' + last_name
  end

end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  before_action :set_guest, only: [:show, :edit, :update, :destroy]

  # GET /guests
  # GET /guests.json
  def index
    @guests = Guest.all
  end

  # GET /guests/1
  # GET /guests/1.json
  def show
  end

  # GET /guests/new
  def new
    @guest = Guest.new
  end

  # GET /guests/1/edit
  def edit
  end

  # POST /guests
  # POST /guests.json
  def create
    @guest = Guest.new(guest_params)

    respond_to do |format|
      if @guest.save
        format.html { redirect_to @guest, notice: 'Guest was successfully created.' }
        format.json { render :show, status: :created, location: @guest }
      else
        format.html { render :new }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guests/1
  # PATCH/PUT /guests/1.json
  def update
    respond_to do |format|
      if @guest.update(guest_params)
        format.html { redirect_to @guest, notice: 'Guest was successfully updated.' }
        format.json { render :show, status: :ok, location: @guest }
      else
        format.html { render :edit }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guests/1
  # DELETE /guests/1.json
  def destroy
    @guest.destroy
    respond_to do |format|
      format.html { redirect_to guests_url, notice: 'Guest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guest
      @guest = Guest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guest_params
      params.require(:guest).permit(:first_name, :last_name, :email, :has_plus_one, group_ids: [])
    end
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/views/guests/_form.html.erb
<%= form_for(@guest, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @guest.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@guest.errors.count, "error") %> prohibited this guest from being saved:</h4>

      <ul>
      <% @guest.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :first_name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :first_name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :last_name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :last_name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :email, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :has_plus_one, class: "col-sm-2 control-label" %>
    <%= f.check_box :has_plus_one, class: 'checkbox' %>
  </div>
  <div class="form-group">
    <div class="col-sm-2 contorl-label"><strong>Groups</strong></div>
    <% Group.all.each do |grp| %>
    <label class="checkbox-inline">
      <%= check_box_tag "guest[group_ids][]", grp.id, f.object.groups.include?(grp), class: "form-control" %>
      <%= grp.name %>
    </label>
    <% end %>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/guests/edit.html.erb
<div class="page-header">
  <%= link_to guests_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @guest, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing guest</h1>
</div>

<%= render 'form' %>

app/views/guests/index.html.erb
<div class="page-header">
  <%= link_to new_guest_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Guest
  <% end %>
  <%= button_to "Send Invitations", {controller: 'invitations', action: 'send_all'}, data: {confirm: 'This will email all of your guests on this list. Are you sure? ONLY DO THIS ONCE'} %>
  <h1>Listing guests</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>First name</th>
            <th>Last name</th>
            <th>Email</th>
            <th>Has Plusone</th>
            <th>Groups</th>
            <th>RSVP</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @guests) do |guest| %>
            <td><%= guest.first_name %></td>
            <td><%= guest.last_name %></td>
            <td><%= guest.email %></td>
            <td><%= guest.has_plus_one %></td>
            <td>
              <% guest.groups.each do |group| %>
                <%= group.name %>
              <% end %>
            </td>
            <% if guest.rsvp == 'no response'%>
              <td><i class="fa fa-spinner"></i></td>
            <% elsif guest.rsvp == 'attending' %>
              <td class="success"><i class="fa fa-thumbs-o-up"></i></td>
            <% else %>
              <td class="danger"><i class="fa fa-thumbs-o-down"></i></td>
            <% end %>
            <td><%= link_to 'Show', guest %></td>
        <td><%= link_to 'Edit', edit_guest_path(guest) %></td>
        <td><%= link_to 'Destroy', guest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/guests/new.html.erb
<div class="page-header">
  <%= link_to guests_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New guest</h1>
</div>

<%= render 'form' %>

app/views/guests/show.html.erb
<div class="page-header">
  <%= link_to guests_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_guest_path(@guest), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show guest</h1>
</div>

<dl class="dl-horizontal">
  <dt>First name:</dt>
  <dd><%= @guest.first_name %></dd>

  <dt>Last name:</dt>
  <dd><%= @guest.last_name %></dd>

  <dt>Email:</dt>
  <dd><%= @guest.email %></dd>

</dl>