config/routes.rb
Rails.application.routes.draw do
  post 'invitations/send_all' => 'invitations#send_all'
  resources :groups
  resources :invitations
  resources :guests
  devise_for :users
  resources :rsvps
  root 'rsvps#index'

end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  belongs_to :guest

  def self.invite_all(guests)
    guests_with_plusone = guests.where(has_plus_one: true)
    guests_without_plusone = guests.where(has_plus_one: false)
   
    InvitationMailer.invite_single(guests_without_plusone).deliver_now
    InvitationMailer.invite_with_plusone(guests_with_plusone).deliver_now
  end


end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :set_invitation, only: [:show, :edit, :update, :destroy]

  def send_all
    @guests = Guest.all
    
    if Invitation.invite_all(@guests)
      redirect_to '/guests',
      notice: 'All guests have been successfully invited'
    else
      redirect_to '/guests',
      notice: 'Failed to send invitations'
    end
    
  end


  # GET /invitations
  # GET /invitations.json
  def index
    @invitations = Invitation.all
  end

  # GET /invitations/1
  # GET /invitations/1.json
  def show
  end

  # GET /invitations/new
  def new
    @invitation = Invitation.new
  end

  # GET /invitations/1/edit
  def edit
  end

  # POST /invitations
  # POST /invitations.json
  def create
    @invitation = Invitation.new(invitation_params)

    respond_to do |format|
      if @invitation.save
        format.html { redirect_to @invitation, notice: 'Invitation was successfully created.' }
        format.json { render :show, status: :created, location: @invitation }
      else
        format.html { render :new }
        format.json { render json: @invitation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invitations/1
  # PATCH/PUT /invitations/1.json
  def update
    respond_to do |format|
      if @invitation.update(invitation_params)
        format.html { redirect_to @invitation, notice: 'Invitation was successfully updated.' }
        format.json { render :show, status: :ok, location: @invitation }
      else
        format.html { render :edit }
        format.json { render json: @invitation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invitations/1
  # DELETE /invitations/1.json
  def destroy
    @invitation.destroy
    respond_to do |format|
      format.html { redirect_to invitations_url, notice: 'Invitation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invitation
      @invitation = Invitation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invitation_params
      params.require(:invitation).permit(:has_plus_one, :guest_id)
    end
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/invitations/_form.html.erb
<%= form_for(@invitation, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @invitation.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@invitation.errors.count, "error") %> prohibited this invitation from being saved:</h4>

      <ul>
      <% @invitation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :has_plus_one, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.check_box :has_plus_one, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :guest_id, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :guest_id, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/invitations/edit.html.erb
<div class="page-header">
  <%= link_to invitations_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @invitation, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing invitation</h1>
</div>

<%= render 'form' %>

app/views/invitations/index.html.erb
<div class="page-header">
  <%= link_to new_invitation_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Invitation
  <% end %>
  <h1>Listing invitations</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Has plus one</th>
            <th>Guest</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @invitations) do |invitation| %>
            <td><%= invitation.has_plus_one %></td>
            <td><%= invitation.guest.full_name %></td>
            <td><%= link_to 'Show', invitation %></td>
        <td><%= link_to 'Edit', edit_invitation_path(invitation) %></td>
        <td><%= link_to 'Destroy', invitation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/invitations/new.html.erb
<div class="page-header">
  <%= link_to invitations_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New invitation</h1>
</div>

<%= render 'form' %>

app/views/invitations/show.html.erb
<div class="page-header">
  <%= link_to invitations_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_invitation_path(@invitation), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show invitation</h1>
</div>

<dl class="dl-horizontal">
  <dt>Has plus one:</dt>
  <dd><%= @invitation.has_plus_one %></dd>

  <dt>Guest:</dt>
  <dd><%= @invitation.guest_id %></dd>

</dl>