config/routes.rb
Rails.application.routes.draw do
  post 'invitations/send_all' => 'invitations#send_all'
  resources :groups
  resources :invitations
  resources :guests
  devise_for :users
  resources :rsvps
  root 'rsvps#index'

end

app/models/rsvp.rb
class Rsvp < ActiveRecord::Base
  belongs_to :guest
  def self.search(search)
    if search
      Rsvp.where('guest LIKE :search OR plusone LIKE :search  OR email LIKE :search OR comment LIKE :search', search: "%#{search}%")
    else
      Rsvp.all
    end
  end

  def comment_preveiw
    comment[0..50].gsub(/\s\w+\s*$/,'...')
  end

  def mark_guest

    # Convert boolean to string
    is_attending = attending ? 'attending' : 'not attending'
    puts(is_attending)
    puts(attending)

    if @guest = Guest.find_by(email: email)
      # Mark guest as having rsvpd
       @guest.update rsvp: is_attending
    else
      # Or create new guest
      @guest = Guest.new email: email,
                         first_name: first_name, 
                         last_name: last_name,
                         rsvp: is_attending
      @guest.save
    end

  end

end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: :create
  skip_before_action :authenticate_user!, only: :create
  before_action :set_rsvp, only: [:show, :edit, :update, :destroy]

  # GET /rsvps
  # GET /rsvps.json
  def index
    @rsvps = Rsvp.search(params[:search])
  end

  # GET /rsvps/1
  # GET /rsvps/1.json
  def show
  end

  # GET /rsvps/new
  def new
    @rsvp = Rsvp.new
  end

  # GET /rsvps/1/edit
  def edit
  end

  # POST /rsvps
  # POST /rsvps.json
  def create
    @rsvp = Rsvp.new(rsvp_params)

      if @rsvp.save
        puts "if was true"
        @rsvp.mark_guest
        RsvpMailer.confirm(@rsvp).deliver
        render plain: "Thank you for the RSVP"
      else
        puts "it was else"
        render plain: "An error has occurred, please contact al@ilseman.com"
      end
  end

  # PATCH/PUT /rsvps/1
  # PATCH/PUT /rsvps/1.json
  def update
    respond_to do |format|
      if @rsvp.update(rsvp_params)
        format.html { redirect_to @rsvp, notice: 'Rsvp was successfully updated.' }
        format.json { render :show, status: :ok, location: @rsvp }
      else
        format.html { render :edit }
        format.json { render json: @rsvp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rsvps/1
  # DELETE /rsvps/1.json
  def destroy
    @rsvp.destroy
    respond_to do |format|
      format.html { redirect_to rsvps_url, notice: 'Rsvp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rsvp
      @rsvp = Rsvp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rsvp_params
      params.permit(:first_name, :last_name, :email, :comment, :attending)
    end
end

app/helpers/rsvps_helper.rb
module RsvpsHelper
end

app/views/rsvps/_form.html.erb
<%= form_for(@rsvp) do |f| %>
  <% if @rsvp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rsvp.errors.count, "error") %> prohibited this rsvp from being saved:</h2>

      <ul>
      <% @rsvp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :guest %><br>
    <%= f.text_field :guest %>
  </div>
  <div class="field">
    <%= f.label :plusone %><br>
    <%= f.text_field :plusone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rsvps/edit.html.erb
<h1>Editing Rsvp</h1>

<%= render 'form' %>

<%= link_to 'Show', @rsvp %> |
<%= link_to 'Back', rsvps_path %>

app/views/rsvps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Rsvps</h1>

<%= form_tag rsvps_path, :method => 'get', :class => 'form-inline' do%>
  <div class="form-group">
    <%= text_field_tag :search, params[:search], :class => "form-control" %>
    <%= button_tag "Search", :name => nil, :class => "btn btn-success" %>
  </div>
<% end %>

<table class="table">
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Email</th>
      <th>Comment</th>
      <th>Attending?</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @rsvps.each do |rsvp| %>
      <tr>
        <td><%= rsvp.first_name %></td>
        <td><%= rsvp.last_name %></td>
        <td><%= rsvp.email %></td>
        <td><%= rsvp.comment %></td>
        <td><%= rsvp.attending %></td>
        <td><%= link_to 'Show', rsvp %></td>
        <td><%= link_to 'Edit', edit_rsvp_path(rsvp) %></td>
        <td><%= link_to 'Destroy', rsvp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rsvp', new_rsvp_path %>

app/views/rsvps/new.html.erb
<h1>New Rsvp</h1>

<%= render 'form' %>

<%= link_to 'Back', rsvps_path %>

app/views/rsvps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Guest:</strong>
  <%= @rsvp.guest %>
</p>

<p>
  <strong>Plusone:</strong>
  <%= @rsvp.plusone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @rsvp.email %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @rsvp.comment %>
</p>

<%= link_to 'Edit', edit_rsvp_path(@rsvp) %> |
<%= link_to 'Back', rsvps_path %>